mariadb:
  host: "localhost"
  port: 3306
  username: "user"
  password: "password"
  database: "nexusban"
h2:
  file: "nexusban"
  username: "user"
  password: "password"
mongodb:
  uri: "mongodb://localhost:27017/db"
  database: "nexusban"
  collection: "nb_"
type: h2
verbose: true