name: NexusBan
version: '1.0-SNAPSHOT'
main: cloud.nextflow.nexusban.NexusBan
api-version: '1.21'
authors: [ Queryzi ]
description: A plugin that can moderate your server!
website: www.nextflow.cloud
depend: [PlaceholderAPI]
commands:
  test:
    aliases:
      - testing
    description: 'A command to test'
    permission: nexusban.test
    usage: /test <ing>
permissions:
  nexusban.*:
    children:
      nexusban.test: true